In [11]:
import pandas as pd
import os

# Get the path to the folder containing the CSV file
folder_path = "C:\\Users\\rzn\\Desktop\\NYC Vehicle Collision Analytics"

# Get the path to the CSV file
csv_file_path = os.path.join(folder_path, "NYC_Vehicle_Collision.csv")

# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(csv_file_path)

# View the head of the DataFrame
df.head()

C:\Users\rzn\AppData\Local\Temp\ipykernel_15040\1393810302.py:11: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file_path)

,CRASH_DATE,CRASH_TIME,BOROUGH,ZIP_CODE,LATITUDE,LONGITUDE,LOCATION,ON_STREET_NAME,CROSS_STREET_NAME,OFF_STREET_NAME,...,CONTRIBUTING_FACTOR_VEHICLE_2,CONTRIBUTING_FACTOR_VEHICLE_3,CONTRIBUTING_FACTOR_VEHICLE_4,CONTRIBUTING_FACTOR_VEHICLE_5,COLLISION_ID,VEHICLE_TYPE_1,VEHICLE_TYPE_2,VEHICLE_TYPE_3,VEHICLE_TYPE_4,VEHICLE_TYPE_5
0,04/14/2020,11:00,NaN,NaN,NaN,NaN,NaN,VERRAZANO BRIDGE UPPER,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4309146.0,Sedan,C1,NaN,NaN,NaN
1,06/13/2016,17:10,NaN,NaN,NaN,NaN,NaN,STATEN ISLAND EXPY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3461754.0,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
2,06/13/2016,17:30,NaN,NaN,NaN,NaN,NaN,MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3461325.0,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
3,08/02/2018,9:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262 BRIGHTON 6 STREET,...,NaN,NaN,NaN,NaN,3953244.0,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
4,06/13/2016,18:00,NaN,NaN,NaN,NaN,NaN,WEST SHORE EXPRESSWAY,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,3461757.0,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN

In [12]:
# Keep the first 120000 rows
df = df[:100000]

# Delete the rest of the rows
#df = df.dropna()

# Get the path to the desktop
desktop_path = os.path.expanduser("~/Desktop")

# Write the updated DataFrame to a new CSV file on the desktop
df.to_csv(os.path.join(desktop_path, "small_csv_file.csv"), index=False)